services:
  - type: web
    name: freedocs-api
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        fromService:
          type: web
          name: freedocs-api
          property: port
    healthCheckPath: /api/health
